name: dacpac-ci
on:
  workflow_dispatch:
    inputs:
      dacpac_solution_dir:
        description: Must specify project directory (comma-separated)
        default: 'Project1,Project2'
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  prepare-matrix:
    runs-on: windows-latest
    outputs:
      directories: ${{ steps.set-matrix.outputs.directories }}
    steps:
      - name: Set Project Directories
        id: set-matrix
        run: |
          $dirs = "${{ inputs.dacpac_solution_dir }}" -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }
          $json = ConvertTo-Json -InputObject @($dirs) -Compress
          echo "directories=$json" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: pwsh

  build-and-pack:
    needs: prepare-matrix
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.prepare-matrix.outputs.directories) }}
    uses: other-repository/.github/workflows/ci.yml@main
    with:
      project-type: dacpac
      dacpac_solution_dir: ${{ matrix.directory }}
    permissions:
      id-token: write
      contents: read
      packages: write
