name: Run Python App

on: 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: Windows-Runner # Similar to choosing a base image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    # - name: Run main.py
    #   run: python main.py
