name: Octopus Deploy Scheduler

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  run-octopus-scheduler:
    runs-on: windows-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          pip install -e .

      - name: Run deployment scheduler script
        env:
          OCTOPUS_DEPLOY_API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
          OCTOPUS_DEPLOY_BASE_URL: ${{ secrets.OCTOPUS_DEPLOY_BASE_URL }}
        run: |
          python cmadevops_deployment_scheduler/octopus_deploy.py
