name: Octopus Deploy on Windows

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    name: Run Octopus Deployment Script
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Octopus Deployment Script
        run: |
          python simplified_octopus_deploy.py
