name: Run ServiceNow Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Set environment variables
      run: |
        echo SNOW_BASE_URL=https://your-instance.service-now.com >> $GITHUB_ENV
        echo SNOW_USERNAME=your-username >> $GITHUB_ENV
        echo SNOW_PASSWORD=your-password >> $GITHUB_ENV
        echo SNOW_AUTOMATION_USER_ID=your-automation-user-id >> $GITHUB_ENV
        echo SNOW_ASSIGNMENT_GROUP_ID=your-assignment-group-id >> $GITHUB_ENV
        echo SNOW_QUERY_TASK_ENDPOINT=/api/now/table/change_task >> $GITHUB_ENV
        echo SNOW_UPDATE_TASK_ENDPOINT=/api/now/table/change_task >> $GITHUB_ENV

    - name: Execute Python script
      run: python service_now_std.py
