name: Build SSIS Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch: # Manual trigger

env:
  ARTIFACTS_DIR: ${{ github.workspace }}/build/artifacts
  OCT_PACKAGE_NAME: EDS-Medicaid
  SSIS_PROJECTS: Medicaid.SQL
  SSIS_OUT: ${{ github.workspace }}\build\ssis
  SSIS_PARAMS: build-assests\Package-Project-Params\
  PACKAGE_FORMAT: zip

jobs:
  build_ssis:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Environment Variables
      run: |
        echo "SSIS_OUT=${{ github.workspace }}\build\ssis" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Create SSIS Output Directory
      run: mkdir "${{ env.SSIS_OUT }}"
      shell: cmd

    - name: Install NuGet Packages
      run: |
        nuget install packages.config -OutputDirectory packages
      shell: cmd

    - name: Build SSIS Projects
      run: |
        echo "*** Building changes from the branch ***"
        $ssisProjects = "${{ env.SSIS_PROJECTS }}".Split(',')
        foreach ($project in $ssisProjects) {
          echo "** Build SSIS: $project **"
          $dtproj = "${{ github.workspace }}\$project\$project.dtproj"
          packages\SSISBuild.2.3.0\tools\ssisbuild.exe "$dtproj" -Configuration "Development" -Protectionlevel DontSaveSensitive -OutputFolder "${{ env.SSIS_OUT }}"
        }
      shell: pwsh

    - name: Copy Parameter Files
      run: |
        xcopy "${{ env.SSIS_PARAMS }}*.params" "${{ env.SSIS_OUT }}\" /O /X /E /H /K
        copy PreDeploy.ps1 "${{ env.SSIS_OUT }}\PreDeploy.ps1"
      shell: cmd

    - name: Install Octopus CLI
      run: |
        Invoke-WebRequest -Uri "https://download.octopusdeploy.com/octopus-tools/latest/OctopusTools.msi" -OutFile "OctopusTools.msi"
        Start-Process msiexec.exe -ArgumentList "/i OctopusTools.msi /quiet /norestart" -Wait
        octo version
      shell: pwsh

    - name: Package Artifacts
      run: |
        octo pack --id=${{ env.OCT_PACKAGE_NAME }}.SSIS --version=1.0.0 --outFolder="${{ env.ARTIFACTS_DIR }}" --basePath="${{ env.SSIS_OUT }}" --format=${{ env.PACKAGE_FORMAT }}
      shell: cmd

    - name: Upload Artifacts


SELECT sum(cumulative_confirmed) as total_confirmed_cases,
       sum(cumulative_deceased) as total_deaths,
       (sum(cumulative_deceased)/sum(cumulative_confirmed))*100 as case_fatality_ratio
FROM `bigquery-public-data.covid19_open_data.covid19_open_data`
WHERE country_name="Italy" AND date BETWEEN 'YYYY-MM-DD' and 'YYYY-MM-DD'
      uses: actions/upload-artifact@v3
      with:
        name: ssis-artifacts
        path: ${{ env.ARTIFACTS_DIR }}


SELECT date
FROM `bigquery-public-data.covid19_open_data.covid19_open_data`
WHERE country_name="Italy" and cumulative_deceased>DEATH
ORDER BY date asc
LIMIT 1

WITH india_cases_by_date AS (
    SELECT date, SUM(cumulative_confirmed) AS cases
    FROM `bigquery-public-data.covid19_open_data.covid19_open_data`
    WHERE country_name ="India" AND date BETWEEN 'YYYY-MM-DD' AND 'YYYY-MM-DD'
    GROUP BY date
    ORDER BY date ASC
), india_previous_day_comparison AS (
    SELECT date, cases, LAG(cases) OVER(ORDER BY date) AS previous_day, cases - LAG(cases) OVER(ORDER BY date) AS net_new_cases
    FROM india_cases_by_date
)
SELECT count(*)
FROM india_previous_day_comparison
WHERE net_new_cases=0
